#typecasting is used to change one datatype to another datatype (But make sure the intercahge of datatype is meaningful)
typestr= str(123)
#typestr = str(typeStr)
print(str(typestr))
print(type(typestr))
